# Generated by Django 5.2.7 on 2025-10-05 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiepilogoMensile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mese', models.CharField(max_length=20, unique=True)),
                ('totale_entrate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totale_uscite', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('guadagno_netto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Riepiloghi Mensili',
            },
        ),
        migrations.CreateModel(
            name='Transazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRATA', 'Entrata'), ('USCITA', 'Uscita')], default='ENTRATA', max_length=7)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_creazione', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
