# Generated by Django 5.2.7 on 2025-10-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riepilogomensile',
            name='guadagno_netto',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
